[versions]
androidxCore = "1.13.0"
androidxTracing = "1.2.0-rc01"
androidDesugarJdkLibs = "2.0.4"
androidxTestExt = "1.1.5"
androidxLifecycle = "2.7.0"
androidxNavigation = "2.7.6"
kotlinxCoroutines = "1.7.3"
okhttp = "4.12.0"
retrofit2 = "2.9.0"
retrofitKotlinxSerializationJson = "1.0.0"
hilt = "2.50"
hiltTest = "2.50"
kotlinxDatetime = "0.5.0"
kotlinxSerializationJson = "1.6.2"
timber = "5.0.1"
androidxComposeBom = "2023.10.01"
androidxHiltNavigationCompose = "1.1.0"
androidxActivity = "1.9.0-rc01"
androidxBrowser = "1.7.0"
androidx-window = "1.3.0"
androidGradlePlugin = "8.1.0-rc01"
androidTools = "31.2.0"
firebaseBom = "32.4.0"
firebaseCrashlyticsPlugin = "2.9.9"
firebasePerfPlugin = "1.4.2"
gmsPlugin = "4.4.0"
kotlin = "1.9.10"
navigationSafeArgsKotlin = "2.7.6"
androidxComposeCompiler = "1.5.3"
androidxEspresso = "3.5.1"
androidxTestCore = "1.5.0"
googleTruth = "1.3.0"
turbine = "1.0.0"
androidxDatastore = "1.0.0"
protobuf = "3.25.1"
protobufPlugin = "0.9.4"
androidxCoreSplashscreen = "1.0.1"
coil = "2.5.0"
accompanist = "0.32.0"
ksp = "1.9.10-1.0.13"
secrets = "2.0.1"
robolectric = "4.11.1"
roborazzi = "1.9.0-alpha-3"
leakcanary = "2.13"

[libraries]

#PublicLibs
androidx-core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "androidxCore" }
androidx-tracing-ktx = { group = "androidx.tracing", name = "tracing-ktx", version.ref = "androidxTracing" }
android-desugarJdkLibs = { group = "com.android.tools", name = "desugar_jdk_libs", version.ref = "androidDesugarJdkLibs" }
androidx-test-ext = { group = "androidx.test.ext", name = "junit-ktx", version.ref = "androidxTestExt" }
androidx-test-core = { group = "androidx.test", name = "core", version.ref = "androidxTestCore" }

google-truth = { group = "com.google.truth", name = "truth", version.ref = "googleTruth" }

# Instrumentation tests
hilt-android-testing = { group = "com.google.dagger", name = "hilt-android-testing", version.ref = "hiltTest" }
hilt-android-compiler = { group = "com.google.dagger", name = "hilt-android-compiler", version.ref = "hiltTest" }
androidx-test-runner = { group = "androidx.test", name = "runner", version.ref = "androidxTestCore" }

# LifeCycle
androidx-lifecycle-runtimeCompose = { group = "androidx.lifecycle", name = "lifecycle-runtime-compose", version.ref = "androidxLifecycle" }
androidx-lifecycle-viewModelCompose = { group = "androidx.lifecycle", name = "lifecycle-viewmodel-compose", version.ref = "androidxLifecycle" }

# Navigation
androidx-navigation-compose = { group = "androidx.navigation", name = "navigation-compose", version.ref = "androidxNavigation" }
androidx-navigation-testing = { group = "androidx.navigation", name = "navigation-testing", version.ref = "androidxNavigation" }

# Coroutines
kotlinx-coroutines-android = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-android", version.ref = "kotlinxCoroutines" }
kotlinx-coroutines-test = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-test", version.ref = "kotlinxCoroutines" }

# Okhttp Interceptor
okhttp-logging = { group = "com.squareup.okhttp3", name = "logging-interceptor", version.ref = "okhttp" }

# Retrofit2
retrofit-core = { group = "com.squareup.retrofit2", name = "retrofit", version.ref = "retrofit2" }

# RetrofitKotlinxSerializationJson
retrofit-kotlin-serialization = { group = "com.jakewharton.retrofit", name = "retrofit2-kotlinx-serialization-converter", version.ref = "retrofitKotlinxSerializationJson" }

# Hilt
hilt-android = { group = "com.google.dagger", name = "hilt-android", version.ref = "hilt" }
hilt-compiler = { group = "com.google.dagger", name = "hilt-compiler", version.ref = "hilt" }

# KotlinxDatetime
kotlinx-datetime = { group = "org.jetbrains.kotlinx", name = "kotlinx-datetime", version.ref = "kotlinxDatetime" }

# KotlinxSerializationJson
kotlinx-serialization-json = { group = "org.jetbrains.kotlinx", name = "kotlinx-serialization-json", version.ref = "kotlinxSerializationJson" }

# Timber
timber = { group = "com.jakewharton.timber", name = "timber", version.ref = "timber" }

# Compose
androidx-compose-bom = { group = "androidx.compose", name = "compose-bom", version.ref = "androidxComposeBom" }

# Material Design 3
androidx-compose-material3 = { group = "androidx.compose.material3", name = "material3" }
androidx-compose-material3-windowSizeClass = { group = "androidx.compose.material3", name = "material3-window-size-class" }

# main APIs for the underlying toolkit systems,
# such as input and measurement/layout
androidx-compose-ui-util = { group = "androidx.compose.ui", name = "ui-util" }
androidx-compose-foundation = { group = "androidx.compose.foundation", name = "foundation" }
androidx-compose-foundation-layout = { group = "androidx.compose.foundation", name = "foundation-layout" }
androidx-compose-runtime = { group = "androidx.compose.runtime", name = "runtime" }

#  Integration with Navigation and Hilt
androidx-hilt-navigation-compose = { group = "androidx.hilt", name = "hilt-navigation-compose", version.ref = "androidxHiltNavigationCompose" }

#  Android Studio Preview support
androidx-compose-ui-tooling-preview = { group = "androidx.compose.ui", name = "ui-tooling-preview" }
androidx-compose-ui-tooling = { group = "androidx.compose.ui", name = "ui-tooling" }

# androidxEspresso
androidx-test-espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "androidxEspresso" }

#  UI Tests
androidx-compose-ui-test = { group = "androidx.compose.ui", name = "ui-test-junit4" }
androidx-compose-ui-testManifest = { group = "androidx.compose.ui", name = "ui-test-manifest" }

# Optional - Integration with activities
androidx-activity-compose = { group = "androidx.activity", name = "activity-compose", version.ref = "androidxActivity" }

# Optional - Integration with browser
androidx-browser = { group = "androidx.browser", name = "browser", version.ref = "androidxBrowser" }

# Optional - Integration with window
androidx-window = { module = "androidx.window:window", version.ref = "androidx-window" }

# Turbine. A small testing library for kotlinx.coroutines Flow
turbine = { group = "app.cash.turbine", name = "turbine", version.ref = "turbine" }

# DataStore
androidx-datastore = { group = "androidx.datastore", name = "datastore", version.ref = "androidxDatastore" }

# Protobuf
protobuf-kotlin-lite = { group = "com.google.protobuf", name = "protobuf-kotlin-lite", version.ref = "protobuf" }
protobuf-protoc = { group = "com.google.protobuf", name = "protoc", version.ref = "protobuf" }

# Splashscreen
androidx-core-splashscreen = { group = "androidx.core", name = "core-splashscreen", version.ref = "androidxCoreSplashscreen" }

# Coil
coil-kt = { group = "io.coil-kt", name = "coil", version.ref = "coil" }
coil-kt-compose = { group = "io.coil-kt", name = "coil-compose", version.ref = "coil" }
coil-kt-svg = { group = "io.coil-kt", name = "coil-svg", version.ref = "coil" }

# Material icon
androidx-compose-material-iconsExtended = { group = "androidx.compose.material", name = "material-icons-extended" }

# Accompanist adaptive
accompanist-adaptive = { module = "com.google.accompanist:accompanist-adaptive", version.ref = "accompanist" }

# Accompanist testharness
accompanist-testharness = { group = "com.google.accompanist", name = "accompanist-testharness", version.ref = "accompanist" }

# lint
lint-api = { group = "com.android.tools.lint", name = "lint-api", version.ref = "androidTools" }

# firebase
firebase-analytics = { group = "com.google.firebase", name = "firebase-analytics-ktx" }
firebase-bom = { group = "com.google.firebase", name = "firebase-bom", version.ref = "firebaseBom" }
firebase-cloud-messaging = { group = "com.google.firebase", name = "firebase-messaging-ktx" }
firebase-crashlytics = { group = "com.google.firebase", name = "firebase-crashlytics-ktx" }
firebase-performance = { group = "com.google.firebase", name = "firebase-perf-ktx" }

# robolectric - Android Unit Testing Framework
robolectric = { group = "org.robolectric", name = "robolectric", version.ref = "robolectric" }
robolectric-shadows = { group = "org.robolectric", name = "shadows-framework", version.ref = "robolectric" }

# roborazzi - A Screenshot tests lib in jvm.
roborazzi = { group = "io.github.takahirom.roborazzi", name = "roborazzi", version.ref = "roborazzi" }

# LeakCanary
leakcanary = { group = "com.squareup.leakcanary", name = "leakcanary-android", version.ref = "leakcanary" }

# Dependencies of the included build-logic
android-gradlePlugin = { group = "com.android.tools.build", name = "gradle", version.ref = "androidGradlePlugin" }
android-tools-common = { group = "com.android.tools", name = "common", version.ref = "androidTools" }
firebase-crashlytics-gradlePlugin = { group = "com.google.firebase", name = "firebase-crashlytics-gradle", version.ref = "firebaseCrashlyticsPlugin" }
firebase-performance-gradlePlugin = { group = "com.google.firebase", name = "perf-plugin", version.ref = "firebasePerfPlugin" }
kotlin-gradlePlugin = { group = "org.jetbrains.kotlin", name = "kotlin-gradle-plugin", version.ref = "kotlin" }
ksp-gradlePlugin = { group = "com.google.devtools.ksp", name = "com.google.devtools.ksp.gradle.plugin", version.ref = "ksp" }

[plugins]
android-application = { id = "com.android.application", version.ref = "androidGradlePlugin" }
android-library = { id = "com.android.library", version.ref = "androidGradlePlugin" }
android-test = { id = "com.android.test", version.ref = "androidGradlePlugin" }
firebase-crashlytics = { id = "com.google.firebase.crashlytics", version.ref = "firebaseCrashlyticsPlugin" }
firebase-perf = { id = "com.google.firebase.firebase-perf", version.ref = "firebasePerfPlugin" }
gms = { id = "com.google.gms.google-services", version.ref = "gmsPlugin" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
navigation-safeargs-kotlin = { id = "androidx.navigation.safeargs.kotlin", version.ref = "navigationSafeArgsKotlin" }
hilt = { id = "com.google.dagger.hilt.android", version.ref = "hilt" }
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
kotlin-serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
protobuf = { id = "com.google.protobuf", version.ref = "protobufPlugin" }
ksp = { id = "com.google.devtools.ksp", version.ref = "ksp" }
secrets = { id = "com.google.android.libraries.mapsplatform.secrets-gradle-plugin", version.ref = "secrets" }
roborazzi = { id = "io.github.takahirom.roborazzi", version.ref = "roborazzi" }


# Plugins defined by this project
tl-android-application = { id = "tl.android.application", version = "unspecified" }
tl-android-application-compose = { id = "tl.android.application.compose", version = "unspecified" }
tl-android-application-firebase = { id = "tl.android.application.firebase", version = "unspecified" }
tl-android-application-flavors = { id = "tl.android.application.flavors", version = "unspecified" }
tl-android-feature = { id = "tl.android.feature", version = "unspecified" }
tl-android-hilt = { id = "tl.android.hilt", version = "unspecified" }
tl-android-library = { id = "tl.android.library", version = "unspecified" }
tl-android-library-compose = { id = "tl.android.library.compose", version = "unspecified" }
tl-android-test = { id = "tl.android.test", version = "unspecified" }
tl-jvm-library = { id = "tl.jvm.library", version = "unspecified" }
